# Generated by Django 3.0 on 2019-12-29 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chapter',
        ),
    ]
